# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # installiere abhaeningkeiten
      - name: Installiere benoetigte Abhaenigkeiten 
        run: make dependencies 

      # Pruefe ob Projekt kompilierbar ist           
      - name: Pruefe ob Projekt kompilierbar ist
        run: make build         

      # Fuehre Unittests des Projekts aus
      - name: Fuehre Unit tests des Projekts aus
        run: make test

